# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
#의존성: 전에 뭘 거쳐서 왔는가? 여럿이 개발하다가 롤백해야할때 주의해야함.
#똑같은 0003_어쩌구 여도 어쩌구가a냐 b냐 를 꼭 적어줘야 함
#마이그레이션은 가급적 한사람만 해야한다
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
