# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160116_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag',
        ),
    ]
