# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160119_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cate',
            new_name='category',
        ),
    ]
